version: '3.8'

services:
  internal-tools:
    image: bxe5056/internal-tools:latest
    # Uncomment to build locally instead of pulling:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - coreAPIToken=${CORE_API_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Add volume mounts if your app needs persistent storage
    # volumes:
    #   - ./data:/app/data
    
    # Optional: Add network configuration
    # networks:
    #   - internal-tools-network

# Optional: Define custom networks
# networks:
#   internal-tools-network:
#     driver: bridge
